# Generated by Django 5.2.1 on 2025-05-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admins',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
